name: felling_good
description: add opinion at bottom
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.5+1

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  data_table_2: ^2.5.6
  flutter_quill: ^7.3.2
  hive: ^2.2.3
  drift: ^2.10.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.3
  cupertino_icons: ^1.0.4
  path_provider: ^2.0.9
  filesystem_picker: ^3.1.0
  file_picker: ^5.2.2
  flutter_quill_extensions: ^0.4.0
  permission_handler: ^10.4.3
  mutex: ^3.0.1
  rating_dialog: ^2.0.4

  note_database:
    path: ./packages/note_database



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator:
  drift_dev:
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/RaleWay-Italic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700

    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC/NotoSansSC-Regular.ttf
        - asset: assets/fonts/NotoSansSC/NotoSansSC-Bold.ttf
